# Question1

In [1]:
list = []
for i in range(2000,3200): 
    if (i%5)!=0 and (i%7==0):
        list = list + [i]
list        

[2002,
 2009,
 2016,
 2023,
 2037,
 2044,
 2051,
 2058,
 2072,
 2079,
 2086,
 2093,
 2107,
 2114,
 2121,
 2128,
 2142,
 2149,
 2156,
 2163,
 2177,
 2184,
 2191,
 2198,
 2212,
 2219,
 2226,
 2233,
 2247,
 2254,
 2261,
 2268,
 2282,
 2289,
 2296,
 2303,
 2317,
 2324,
 2331,
 2338,
 2352,
 2359,
 2366,
 2373,
 2387,
 2394,
 2401,
 2408,
 2422,
 2429,
 2436,
 2443,
 2457,
 2464,
 2471,
 2478,
 2492,
 2499,
 2506,
 2513,
 2527,
 2534,
 2541,
 2548,
 2562,
 2569,
 2576,
 2583,
 2597,
 2604,
 2611,
 2618,
 2632,
 2639,
 2646,
 2653,
 2667,
 2674,
 2681,
 2688,
 2702,
 2709,
 2716,
 2723,
 2737,
 2744,
 2751,
 2758,
 2772,
 2779,
 2786,
 2793,
 2807,
 2814,
 2821,
 2828,
 2842,
 2849,
 2856,
 2863,
 2877,
 2884,
 2891,
 2898,
 2912,
 2919,
 2926,
 2933,
 2947,
 2954,
 2961,
 2968,
 2982,
 2989,
 2996,
 3003,
 3017,
 3024,
 3031,
 3038,
 3052,
 3059,
 3066,
 3073,
 3087,
 3094,
 3101,
 3108,
 3122,
 3129,
 3136,
 3143,
 3157,
 3164,
 3171,
 3178,
 3192,
 3199]

# Question 2

In [24]:
def fact(n):
    a = 1
    if (n==0):
        return a
    else:
        for i in range(1,n+1):
            a = a*i
        return a        
val = int(input())
fact(val)        

3


6

# Question3

In [26]:
dictionary= {}
val = int( input("introduisez une valeur: "))
for i in range(1,val+1):
    dictionary[i] = i*i
    
    
dictionary

introduisez une valeur: 8


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

# Question 4

In [49]:
def missing_char(a, n):
    a = a.replace(" ","")
    if n in range(len(a)):
        b = a[:n]
        c = a[n+1:]
        a = b+c
        print(a)
missing_char("hello", 3)        

helo


# Question 5

In [122]:
import numpy as np 
A = np.array([[1,2],[3,4],[5,6]])
print(A)
A.tolist()

[[1 2]
 [3 4]
 [5 6]]


[[1, 2], [3, 4], [5, 6]]

# Question 6

In [128]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
print(array1)
array2 = np.array([6, 7, 8, 9, 10])
print(array2)
covar = np.cov(array1,array2)
print(covar)

[1 2 3 4 5]
[ 6  7  8  9 10]
[[2.5 2.5]
 [2.5 2.5]]


In [172]:
import math
H,C = 30,50
liste= []
liste = liste + [int(x) for x in input().split(",")]
for D in liste:  
    Q = math.sqrt((2*C*D)/H)
    print(f" la valeur de Q est : {Q}")



20,30,50
 la valeur de Q est : 8.16496580927726
 la valeur de Q est : 10.0
 la valeur de Q est : 12.909944487358056
